#!/bin/sh

echo "file changes between head_ref and base_ref"
git log --name-only --oneline --pretty="format:" "origin/$1"..."origin/$2"

if git log --name-only --oneline --pretty="format:" "origin/$1"..."origin/$2" | grep -sP "$3"
then
    echo "files matching pattern $3 remain unchanged"
    exit 0
else
    echo "files matching pattern $3 have been changed!"
    exit 1
fi
