name: Pull Request Checks
on: pull_request

jobs:
  changelog-updated:
    name: CHANGELOG updated
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: .github/scripts/file-changed-check "${{ github.head_ref }}" "${{ github.base_ref }}" "CHANGELOG\.md"
  unit-tests-updated:
    name: Unit tests updated
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: .github/scripts/file-changed-check "${{ github.head_ref }}" "${{ github.base_ref }}" "test/[A-Za-z0-9_]+\.jl"
  docs-updated:
    name: Documentation updated
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: .github/scripts/file-changed-check "${{ github.head_ref }}" "${{ github.base_ref }}" "docs/[A-Za-z0-9_/]+\.md|examples/[A-Za-z0-9_/]+\.ipynb"
  dependencies-unchanged:
    name: Dependencies unchanged
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: .github/scripts/file-unchanged-check "${{ github.head_ref }}" "${{ github.base_ref }}" "Project\.toml"
